name: Vitest tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  vitest:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.9.1
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install modules
        run: npm install
      - name: Run vitest
        run: npm run test:unit
