name: e2e tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  cypress:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.9.1
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          start: npm start
          wait-on: "http://localhost:5173"
